GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/info/

###
GET http://localhost:3001/api/persons/6936dba9934b8c1c3ce8ead2

###
DELETE http://localhost:3001/api/persons/4

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Zrubabel Kodesh",
    "number": "666-0055667"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Mike Green"
}

###
PUT http://localhost:3001/api/persons/69383199520752e64903ba4c
Content-Type: application/json

{
    "name": "Zrubabel Kodesh",
    "number": "00000000"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "number": "052-5933269"
}